# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo_master.xdc

# Block Designs: bd/Pspwm/Pspwm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pspwm || ORIG_REF_NAME==Pspwm}]

# IP: bd/Pspwm/ip/Pspwm_processing_system7_0_0/Pspwm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pspwm_processing_system7_0_0 || ORIG_REF_NAME==Pspwm_processing_system7_0_0}]

# IP: bd/Pspwm/ip/Pspwm_processing_system7_0_axi_periph_0/Pspwm_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pspwm_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==Pspwm_processing_system7_0_axi_periph_0}]

# IP: bd/Pspwm/ip/Pspwm_rst_processing_system7_0_100M_0/Pspwm_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pspwm_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Pspwm_rst_processing_system7_0_100M_0}]

# IP: bd/Pspwm/ip/Pspwm_xbar_0/Pspwm_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pspwm_xbar_0 || ORIG_REF_NAME==Pspwm_xbar_0}]

# IP: bd/Pspwm/ip/Pspwm_myip_pspwm_0_1/Pspwm_myip_pspwm_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pspwm_myip_pspwm_0_1 || ORIG_REF_NAME==Pspwm_myip_pspwm_0_1}]

# IP: bd/Pspwm/ip/Pspwm_Alto_nivel_0_1/Pspwm_Alto_nivel_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pspwm_Alto_nivel_0_1 || ORIG_REF_NAME==Pspwm_Alto_nivel_0_1}]

# IP: bd/Pspwm/ip/Pspwm_auto_pc_0/Pspwm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Pspwm_auto_pc_0 || ORIG_REF_NAME==Pspwm_auto_pc_0}]

# XDC: bd/Pspwm/ip/Pspwm_processing_system7_0_0/Pspwm_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Pspwm_processing_system7_0_0 || ORIG_REF_NAME==Pspwm_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/Pspwm/ip/Pspwm_rst_processing_system7_0_100M_0/Pspwm_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Pspwm_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Pspwm_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/Pspwm/ip/Pspwm_rst_processing_system7_0_100M_0/Pspwm_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Pspwm_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Pspwm_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/Pspwm/ip/Pspwm_rst_processing_system7_0_100M_0/Pspwm_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/Pspwm/ip/Pspwm_xbar_0/Pspwm_xbar_0_ooc.xdc

# XDC: bd/Pspwm/ip/Pspwm_auto_pc_0/Pspwm_auto_pc_0_ooc.xdc

# XDC: bd/Pspwm/Pspwm_ooc.xdc
